create table profiles
(
    id           int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      int NOT NULL,
    phone        varchar(20)                      DEFAULT NULL,
    nicename     varchar(255)             DEFAULT NULL,
    avatar       int                      DEFAULT NULL,
    company_name varchar(255)             DEFAULT NULL,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deleted_at   TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    constraint profile_user_id_fk
        foreign key (user_id) references users (id)
            on delete cascade

);
CREATE DOMAIN phone AS text CHECK(
        octet_length(VALUE)
            BETWEEN 1/*+*/ + 8  --https://stackoverflow.com/questions/14894899/what-is-the-minimum-length-of-a-valid-international-phone-number
            AND 1/*+*/ + 15 --https://en.wikipedia.org/wiki/E.164 and https://en.wikipedia.org/wiki/Telephone_numbering_plan
            + 3  --reserved for depersonalization
        AND VALUE ~ '^\+\d+$' --international E.164 format
    );
COMMENT ON DOMAIN phone IS 'Phone Number E.164';